import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/smooth_scrol";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <SmoothScroll />
        {children}
        <div
          className="fixed bottom-0 left-0 w-full h-[10vh] pointer-events-none z-50 
    backdrop-blur-md 
    [mask-image:linear-gradient(to_top,black,transparent)] 
    [mask-mode:match-source]"
        ></div>
      </body>
    </html>
  );
}
